### ISSUE TITLE
Form validatie

### ISSUE THREAD

**Issue by vasilisvg** [camille500/CSS-To-The-Rescue#15]
Kijk eens naar [dit formulier](https://codepen.io/joostf/pen/VKyPxk) om te zien of je er iets van kunt gebruiken. Let er ook op dat de validatie-states zichtbaar zijn. Het rode lijntje op de donkerblauwe achtergrond zijn niet duidelijk.

**Comment by camille500** [comment]
Aangepast in 'week3' versie, extra validatie toegevoegd
