### ISSUE TITLE
Plaatje met onderschrift is moeilijker …

### ISSUE THREAD

**Issue by vasilisvg** [camille500/CSS-To-The-Rescue#16]
Het plaatje moet _altijd_ helemaal zichtbaar zijn in elke viewport. Dus maximaal `100vh`, en maximaal `100vw`. Bovendien moet je ook altijd kunnen zien dat er een onderschrift is. En dit moet werken met een landscape en een portrait plaatje …
En kan je je nog herinneren hoeveel `em` breed een paragraaf maximaal mag zijn?

**Comment by camille500** [comment]
Changed this in the new site 'week3'
