### ISSUE TITLE
* selector

### ISSUE THREAD

**Issue by rikschennink** [camille500/CSS-To-The-Rescue#7]
De wildcard selector is super handig. Maar pas op met een reset op alles. Beter niet doen > je reset onbewust mogelijk ook standaard stijlen die je wel wil hebben. Daarnaast resulteerde dit "vroeger" ook nog wel eens in onverwachte bugs. Ongetwijfeld dat dit nu nog steeds een issue is met 20.000 verschillende Android devices.

**Comment by camille500** [comment]
Properties from wildcard selector are now placed in the body selector
