### ISSUE TITLE
ol.chat

### ISSUE THREAD

**Issue by rikschennink** [camille500/CSS-To-The-Rescue#8]
Let op je specificiteit (https://specificity.keegan.st) minder specifiek is beter (dan is later overreden makkelijker). De CSS parser werkt van rechts naar links dus `ol.chat` is dubbel zolang .chat niet mogelijk is op een ander element, `.chat` is voldoende. Daarnaast kan je de `li` overslaan bij het selecteren van de `p` -> `.chat p`.

**Comment by camille500** [comment]
Edit for all classes is style.css
